---
default_stages: [commit, push]
default_language_version:
  # force all unspecified Python hooks to run python3
  python: python3
minimum_pre_commit_version: "1.20.0"
repos:
  - repo: meta
    hooks:
      - id: identity
      - id: check-hooks-apply
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-ast
      - id: check-builtin-literals
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-executables-have-shebangs
        exclude: ^rubycritic/assets.*$
      - id: check-json
      - id: check-merge-conflict
      - id: check-toml
      - id: check-xml
        exclude: ^docs/assets/xsl/rss\.xsl$|^docs/feed\.xslt\.xml$|^docs/opensearch\.xml$|^docs/rss\.xml$|^logorama/feed\.xml$
      - id: check-yaml
      - id: debug-statements
      - id: detect-private-key
      - id: end-of-file-fixer
        exclude: ^charts/assets/.*$|^charts/lang/README\.de\.md$|^charts/log\.txt$|^charts/README\.md$|^docs/assets/js/.*$|^docs/assets/games/.*$|rubycritic/.*$
      - id: fix-byte-order-marker
      - id: mixed-line-ending
      # - id: pretty-format-json
      - id: requirements-txt-fixer
      - id: trailing-whitespace
        exclude: ^rubycritic/.*$
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        name: Run black on Python files
  # - repo: https://github.com/asottile/dead
  #  rev: v1.5.0
  #  hooks:
  #    - id: dead
  #      name: Dead simple Python dead code detection
  #      exclude: ^doc/source/conf\.py$|^scrapers/python/scrapy/github/spider\.py$
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.9.0
    hooks:
      - id: reorder-python-imports
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 3.0.0
    hooks:
      - id: markdownlint # Configure in .mdlrc
      - id: reek
      - id: rubocop
        args: ["--autocorrect-all"]
      - id: shellcheck
  - repo: https://github.com/Lucas-C/pre-commit-hooks
    rev: v1.4.2
    hooks:
      - id: forbid-tabs
        exclude: ^doc/Makefile$|go\.mod$|go\.sum$|^rubycritic/assets.*$|.*\.go$
      - id: remove-tabs
        exclude: ^doc/Makefile$|go\.mod$|go\.sum$|^rubycritic/assets.*$|.*\.go$
  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: python-check-mock-methods
      - id: python-no-eval
      - id: python-no-log-warn
  - repo: https://github.com/igorshubovych/markdownlint-cli
    rev: v0.33.0
    hooks:
      - id: markdownlint
        name: Run markdownlint
        entry: markdownlint -c .github/linters/.markdown-lint.yml .
        args: [--ignore=doc/venv, --ignore=node_modules]
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.29.0
    hooks:
      - id: yamllint
        name: Check YAML files with yamllint
        entry: yamllint --strict -c .github/linters/.yaml-lint.yml .
        types: [yaml]
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
      - id: bandit
  - repo: https://github.com/pycqa/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        entry: flake8 --config=".github/linters/.flake8"
  - repo: https://github.com/pycqa/pylint
    rev: v2.17.0
    hooks:
      - id: pylint
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.4
    hooks:
      - id: codespell
        entry: codespell -I codespell.txt ./doc/source
        exclude: ^assets/.*$|^charts/.*$|^docs/assets/.*$|^eclipse-cheatsheets-to-dita-to-pdf/.*$|^Gemfile\.lock$|^go\.work\.sum$|^logorama/.*$|^rubycritic/.*$|^ruby-eclipse-cheatsheets-to-dita/.*$|^tests/spelling/.*$
  # - repo: https://github.com/syntaqx/git-hooks
  #  rev: v0.0.16
  #  hooks:
  #    - id: go-fmt
  #    - id: go-test
  #    - id: go-mod-tidy
