AllCops:
  Exclude:
    - vendor/**/*
  NewCops: enable
  TargetRubyVersion: 2.7.2

### LAYOUT
Layout/LineLength:
  Enabled: false

Layout/EndOfLine:
  Enabled: false

Layout/SpaceAroundEqualsInParameterDefault:
  EnforcedStyle: no_space

Layout/SpaceBeforeBlockBraces:
  EnforcedStyle: no_space

Layout/SpaceInsideBlockBraces:
  EnforcedStyle: no_space
  SpaceBeforeBlockParameters: false

Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space

Lint/DuplicateBranch:
  Enabled: false

### METRICS
Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 44

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 130

Metrics/ParameterLists:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

### STYLING
Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/GuardClause:
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Style/Semicolon:
  Enabled: false
