sudo: false

matrix:
  include:
    - language: python
      python:
        - "3.7"
      install: "pip install -r requirements.txt"
      script:
        - pylint --version
        - find . -name "*.py" | xargs pylint --disable=C0103,C0114,W0221
        - flake8 --version
        - flake8 --ignore=E501

    - language: go
      go:
        - 1.13.x
      before_install:
        - curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.52.2
        - if [[ "${GO111MODULE}" = "on" ]]; then mkdir "${HOME}/go"; export GOPATH="${HOME}/go"; fi
      install:
        - if [[ "${GO111MODULE}" = "on" ]]; then go mod download; fi
        - if [[ "${GO111MODULE}" = "on" ]]; then export PATH="${GOPATH}/bin:${GOROOT}/bin:${PATH}"; fi
      go_import_path: github.com/slurpcode/slurp
      script:
        - golangci-lint run
        - go test -race -covermode atomic -coverprofile=profile.cov ./...
