# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Fuchsia Programming
email:
description: >- # this means to ignore newlines until "baseurl:"
  We like Fuchsia Flowers.  Fuchsia Programming is the place for
  Fuchsia enthusiasts, whether it's pink, purple or fuchsia we
  have it all for you !?!?!!! :)
baseurl: /slurp # the subpath of your site, e.g. /blog
url: https://slurpcode.github.io/ # the base hostname & protocol for your site, e.g. http://example.com
repository: https://github.com/slurpcode/slurp
twitter_username:
github_username: slurpcode
paginate: 20
feed:
  path: feed.xml
author: jbampton
disqus:
  shortname: fuchsia-programming
collections:
  docs:
    permalink: "/:collection/:path/"
    output: true
defaults:
  - scope:
      path: _docs
      type: docs
    values:
      color: white
      layout: docs
      page-type: docs
  - scope:
      path: _posts
      type: posts
    values:
      layout: post
# Build settings
markdown: kramdown
sass:
  style: compressed
theme: minima
future: true
plugins:
  - jekyll-avatar
  - jekyll-feed
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - .gitignore
  - assets/python/
  - server
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
