name: Lint

on: [pull_request]

jobs:
  merge-conflict:
    name: 🥃 Merge Conflict
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check merge conflict
        run: grep "^<<<<<<< HEAD" $(git ls-files | xargs) && exit 1 || true
  misspell:
    name: 🥛 Check Spelling
    runs-on: ubuntu-latest
    steps:
      - name: 🍒 Check Out
        uses: actions/checkout@v2
      - name: 🍅 Install
        run: |
          wget -O - -q https://git.io/misspell | sh -s -- -b .
      - name: 🌶️ Misspell
        run: |
          git ls-files --empty-directory | grep -v charts/assets/js | grep -v charts/config/de.yml | grep -v charts/lang/README.de.md | grep -v charts/site.yml | grep -v doc/source/codewars.md | grep -v docs/assets/games | grep -v docs/assets/js | grep -v rubycritic | xargs ./misspell -error
  trailing-whitespace:
    name: 🧋 Trailing whitespace
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: 🧹 Check for trailing whitespace
        run: "! git grep -EIn $'[ \t]+$' | grep -v rubycritic"
