name: Check Markdown links

on: [pull_request]

permissions:  # added using https://github.com/step-security/secure-workflows
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - uses: gaurav-nelson/github-action-markdown-link-check@v1
        with:
          base-branch: 'main'
          config-file: 'mlc_config.json'
          use-quiet-mode: 'yes'
          use-verbose-mode: 'yes'
