name: Check Markdown links

on: [pull_request]

permissions: 
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Linkspector
        uses: linkspector/github-action@v1
        with:
          config-file: 'linkspector_config.json'
          quiet: true  # equivalent to quiet mode
          verbose: true  # equivalent to verbose mode
