name: Lint Code Base

on: [pull_request]

jobs:
  build:
    name: GitHub Super Linter
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          # Full git history is needed to get a proper list of changed files within `super-linter`
          fetch-depth: 0
      - uses: github/super-linter@v4
        env:
          ERROR_ON_MISSING_EXEC_BIT: true
          VALIDATE_BASH: true
          VALIDATE_BASH_EXEC: true
          VALIDATE_GO: true
          VALIDATE_RUBY: true
          # VALIDATE_EDITORCONFIG: true
          VALIDATE_MARKDOWN: true
          VALIDATE_PHP: true
          VALIDATE_YAML: true
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
