name: Deploy

on:
  push:
    branches:
      - main

jobs:
  magic:
    if: github.repository == 'slurpcode/slurp'
    runs-on: ubuntu-latest
    name: Magic
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.1.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers.dev/magic'
          command: deploy
  preston:
    if: github.repository == 'slurpcode/slurp'
    runs-on: ubuntu-latest
    name: Preston
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4
      - name: Deploy
        uses: cloudflare/wrangler-action@v3.1.1
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers.dev/preston'
          command: deploy
