name: Deploy

on:
  push:
    branches:
      - master

jobs:
  magic:
    runs-on: ubuntu-latest
    name: Magic
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers.dev/magic'
  preston:
    runs-on: ubuntu-latest
    name: Preston
    steps:
      - uses: actions/checkout@v2
      - name: Publish
        uses: cloudflare/wrangler-action@1.2.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'workers.dev/preston'
